// English source text -> es, de, fr, ko, pt-BR, ru, it.
export const additionalText: Record<string, readonly string[]> = Object.fromEntries(`
Octave down|Bajar una octava|Oktave tiefer|Une octave plus bas|한 옥타브 아래|Uma oitava abaixo|На октаву ниже|Un’ottava sotto
Octave up|Subir una octava|Oktave höher|Une octave plus haut|한 옥타브 위|Uma oitava acima|На октаву выше|Un’ottava sopra
Semitone down|Bajar un semitono|Halbton tiefer|Un demi-ton plus bas|반음 아래|Um semitom abaixo|На полтона ниже|Un semitono sotto
Semitone up|Subir un semitono|Halbton höher|Un demi-ton plus haut|반음 위|Um semitom acima|На полтона выше|Un semitono sopra
Adjust by note name|Ajustar por nombre de nota|Nach Notennamen einstellen|Ajuster par nom de note|음이름으로 조정|Ajustar pelo nome da nota|Настроить по названию ноты|Regola per nome della nota
Tap the staff or drag vertically to choose the lowest and highest notes. Use ♭/♯ for semitones and ±8 for octaves.|Toca el pentagrama o arrastra verticalmente para elegir las notas límite. Usa ♭/♯ para semitonos y ±8 para octavas.|Tippe auf das Notensystem oder ziehe vertikal, um die tiefste und höchste Note zu wählen. ♭/♯ ändert Halbtöne, ±8 Oktaven.|Touchez la portée ou glissez verticalement pour choisir les notes extrêmes. ♭/♯ ajuste les demi-tons et ±8 les octaves.|오선보를 누르거나 위아래로 드래그해 최저음과 최고음을 선택하세요. ♭/♯는 반음, ±8은 옥타브를 조정합니다.|Toque na pauta ou arraste verticalmente para escolher as notas limites. Use ♭/♯ para semitons e ±8 para oitavas.|Нажмите на нотный стан или перетащите по вертикали, чтобы выбрать границы диапазона. ♭/♯ меняет полутоны, ±8 — октавы.|Tocca il pentagramma o trascina verticalmente per scegliere le note estreme. ♭/♯ regola i semitoni, ±8 le ottave.
Twilight Dragon|Dragoncito del crepúsculo|Kleiner Dämmerungsdrache|Petit dragon du crépuscule|황혼의 아기 용|Dragãozinho do crepúsculo|Сумеречный дракончик|Draghetto del crepuscolo
Hokkaido Snowbird|Mito de Hokkaido|Schwanzmeise aus Hokkaido|Mésange à longue queue de Hokkaido|홋카이도 오목눈이|Chapim de Hokkaido|Длиннохвостая синица Хоккайдо|Codibugnolo di Hokkaido
New Zealand Kiwi|Kiwi de Nueva Zelanda|Neuseeland-Kiwi|Kiwi de Nouvelle-Zélande|뉴질랜드 키위|Kiwi da Nova Zelândia|Новозеландский киви|Kiwi della Nuova Zelanda
Taiwan Black Bear|Oso negro de Taiwán|Taiwanischer Schwarzbär|Ours noir de Taïwan|타이완흑곰|Urso-negro de Taiwan|Тайваньский чёрный медведь|Orso nero di Taiwan
River Otter|Nutria de río|Flussotter|Loutre de rivière|강수달|Lontra de rio|Речная выдра|Lontra di fiume
Australian Kangaroo|Canguro australiano|Australisches Känguru|Kangourou australien|호주 캥거루|Canguru australiano|Австралийский кенгуру|Canguro australiano
Sunshine Lion|León soleado|Sonnenlöwe|Lion du soleil|햇살 사자|Leão do sol|Солнечный лев|Leone del sole
American Shorthair|Gato americano de pelo corto|Amerikanisch Kurzhaar|American Shorthair|아메리칸 쇼트헤어|Gato americano de pelo curto|Американская короткошёрстная|Gatto americano a pelo corto
Little Blue Penguin|Pingüino azul|Zwergpinguin|Petit manchot bleu|쇠푸른펭귄|Pinguim-azul|Малый голубой пингвин|Pinguino minore blu
Expression practice|Práctica de expresión|Ausdruck üben|Pratique de l’expression|연주 기호 연습|Prática de expressão|Практика выразительности|Pratica espressiva
Expression guide|Guía de expresión|Zeichenerklärung|Guide des signes d’expression|연주 기호 설명|Guia de expressão|Обозначения выразительности|Guida ai segni espressivi
Add dynamics, staccato, tenuto and accents to the score and playback.|Añade dinámicas, staccato, tenuto y acentos a la partitura y la reproducción.|Dynamik, Staccato, Tenuto und Akzente in Noten und Wiedergabe ergänzen.|Ajoute nuances, staccato, tenuto et accents à la partition et à la lecture.|셈여림, 스타카토, 테누토, 악센트를 악보와 재생에 반영합니다.|Adiciona dinâmica, staccato, tenuto e acentos à partitura e à reprodução.|Добавляет динамику, стаккато, тенуто и акценты в ноты и воспроизведение.|Aggiunge dinamiche, staccato, tenuto e accenti alla partitura e alla riproduzione.
p = soft, mp = moderately soft, mf = moderately loud, f = loud; dynamics continue until the next marking. A dot means staccato (short), a dash means tenuto (full length), and > means accent.|p = suave, mp = moderadamente suave, mf = moderadamente fuerte, f = fuerte; dura hasta la siguiente indicación. Punto: staccato (corto); raya: tenuto (duración completa); >: acento.|p = leise, mp = mäßig leise, mf = mäßig laut, f = laut; gilt bis zur nächsten Angabe. Punkt: Staccato (kurz); Strich: Tenuto (volle Dauer); >: Akzent.|p = doux, mp = modérément doux, mf = modérément fort, f = fort ; jusqu’à la prochaine nuance. Point : staccato (court) ; trait : tenuto (durée entière) ; > : accent.|p는 여리게, mp는 조금 여리게, mf는 조금 세게, f는 세게이며 다음 기호까지 유지합니다. 점은 스타카토(짧게), 가로선은 테누토(음가를 충분히), >는 악센트입니다.|p = suave, mp = moderadamente suave, mf = moderadamente forte, f = forte; vale até a próxima indicação. Ponto: staccato (curto); traço: tenuto (duração inteira); >: acento.|p — тихо, mp — умеренно тихо, mf — умеренно громко, f — громко; до следующего обозначения. Точка — стаккато (коротко), черта — тенуто (полная длительность), > — акцент.|p = piano, mp = mezzopiano, mf = mezzoforte, f = forte; vale fino alla prossima indicazione. Punto: staccato (breve); trattino: tenuto (durata piena); >: accento.
Main navigation|Navegación principal|Hauptnavigation|Navigation principale|주 탐색|Navegação principal|Главная навигация|Navigazione principale
My studio|Mi estudio|Mein Studio|Mon studio|내 연습실|Meu estúdio|Моя студия|Il mio studio
stars|estrellas|Sterne|étoiles|별 포인트|estrelas|звёзды|stelle
A little progress, recorded.|Un pequeño avance registrado.|Ein kleiner Fortschritt, festgehalten.|Un petit progrès enregistré.|작은 성장을 기록했어요.|Um pequeno progresso registrado.|Небольшой прогресс записан.|Un piccolo progresso registrato.
Give your practice a little recognition.|Reconoce tu esfuerzo de hoy.|Würdige deine Übung.|Reconnaissez votre effort.|오늘의 연습을 인정해 주세요.|Valorize sua prática.|Отметьте свой труд.|Riconosci il valore della tua pratica.
Keep revisiting this study; rewards are counted once.|Puedes repetir este ejercicio; la recompensa se recibe una vez.|Du kannst weiterüben; die Belohnung gibt es einmal.|Vous pouvez rejouer cet exercice ; la récompense est unique.|계속 연습할 수 있어요. 보상은 한 번만 지급됩니다.|Pode repetir o estudo; a recompensa é recebida uma vez.|Продолжайте упражнение; награда выдаётся один раз.|Puoi ripetere lo studio; la ricompensa si riceve una volta.
After 60 seconds in the foreground, confirm your practice. Earn stars for the first 3 each day.|Tras 60 segundos con la página activa, confirma tu práctica. Las primeras 3 del día dan estrellas.|Nach 60 Sekunden im Vordergrund kannst du bestätigen. Die ersten 3 Übungen am Tag bringen Sterne.|Après 60 secondes au premier plan, confirmez. Les 3 premières pratiques du jour rapportent des étoiles.|화면을 열고 60초간 연습한 뒤 완료를 확인하세요. 매일 처음 3회에 별 포인트를 받아요.|Após 60 segundos com a página ativa, confirme. As primeiras 3 práticas do dia dão estrelas.|После 60 секунд с открытой страницей подтвердите занятие. Первые 3 за день дают звёзды.|Dopo 60 secondi in primo piano, conferma. Le prime 3 pratiche del giorno danno stelle.
Completed|Completado|Abgeschlossen|Terminé|완료|Concluído|Завершено|Completato
sec|s|Sek.|s|초|s|с|s
Complete practice|Completar práctica|Übung abschließen|Terminer la pratique|연습 완료|Concluir prática|Завершить занятие|Completa la pratica
This browser cannot save progress; it may be lost when closed.|Este navegador no puede guardar el progreso; podría perderse al cerrarlo.|Dieser Browser kann Fortschritte nicht speichern; beim Schließen können sie verloren gehen.|Ce navigateur ne peut pas enregistrer les progrès ; ils peuvent être perdus à la fermeture.|이 브라우저는 성장 기록을 저장할 수 없어 닫으면 사라질 수 있어요.|Este navegador não pode salvar o progresso; ele pode ser perdido ao fechar.|Браузер не может сохранить прогресс; при закрытии он может пропасть.|Questo browser non può salvare i progressi; potrebbero andare persi alla chiusura.
Close|Cerrar|Schließen|Fermer|닫기|Fechar|Закрыть|Chiudi
Top up to 10,000 test stars|Recargar hasta 10.000 estrellas de prueba|Auf 10.000 Teststerne auffüllen|Recharger à 10 000 étoiles de test|테스트 포인트 10,000까지 충전|Completar até 10.000 estrelas de teste|Пополнить до 10 000 тестовых звёзд|Ricarica fino a 10.000 stelle di prova
Owned|En tu colección|Im Besitz|Déjà acquis|보유 중|Já adquirido|В коллекции|Già posseduto
Free|Gratis|Kostenlos|Gratuit|무료|Grátis|Бесплатно|Gratis
Equipped|En uso|Ausgewählt|Utilisé|사용 중|Em uso|Используется|In uso
Use now|Usar|Verwenden|Utiliser|적용|Usar|Применить|Usa
Unlock|Canjear|Einlösen|Débloquer|교환|Resgatar|Получить|Sblocca
Preview|Vista previa|Vorschau|Aperçu|미리 보기|Prévia|Предпросмотр|Anteprima
Metronome pet collection|Colección de compañeros metrónomo|Metronom-Begleiter sammeln|Collection de compagnons métronomes|메트로놈 친구 컬렉션|Coleção de amigos metrônomos|Коллекция друзей-метрономов|Collezione di amici metronomi
A little effort, a little sparkle.|Un pequeño esfuerzo merece brillar.|Jede Mühe verdient ein Funkeln.|Chaque effort mérite de briller.|작은 노력도 반짝일 가치가 있어요.|Todo esforço merece brilhar.|Каждое усилие заслуживает награды.|Ogni sforzo merita di brillare.
Keep practicing to reach the next level.|Sigue practicando para subir de nivel.|Übe weiter für die nächste Stufe.|Continuez pour atteindre le niveau suivant.|계속 연습해서 다음 레벨로 올라가세요.|Continue praticando para subir de nível.|Продолжайте заниматься, чтобы повысить уровень.|Continua a esercitarti per salire di livello.
Companion preview|Vista del compañero|Begleiter-Vorschau|Aperçu du compagnon|친구 미리 보기|Prévia do companheiro|Просмотр спутника|Anteprima del compagno
ALWAYS FREE|SIEMPRE GRATIS|IMMER KOSTENLOS|TOUJOURS GRATUIT|항상 무료|SEMPRE GRÁTIS|ВСЕГДА БЕСПЛАТНО|SEMPRE GRATIS
ANIMAL METRONOMES|METRÓNOMOS ANIMALES|TIER-METRONOME|MÉTRONOMES ANIMAUX|동물 메트로놈|METRÔNOMOS ANIMAIS|ЗВЕРЯТА-МЕТРОНОМЫ|METRONOMI ANIMALI
Mimo · Original companion|Mimo · Compañero original|Mimo · Ursprünglicher Begleiter|Mimo · Compagnon original|미모 · 기본 친구|Mimo · Companheiro original|Мимо · Первый спутник|Mimo · Compagno originale
Your original green metronome. Always here for you.|Tu primer metrónomo verde. Siempre a tu lado.|Dein ursprüngliches grünes Metronom. Immer für dich da.|Votre premier métronome vert. Toujours à vos côtés.|처음부터 함께한 초록 메트로놈이에요. 언제든 돌아오세요.|Seu primeiro metrônomo verde. Sempre ao seu lado.|Ваш первый зелёный метроном. Всегда рядом.|Il tuo primo metronomo verde. Sempre al tuo fianco.
Meet your companion before unlocking.|Conoce a tu compañero antes de canjearlo.|Lerne deinen Begleiter vor dem Einlösen kennen.|Découvrez votre compagnon avant de le débloquer.|교환하기 전에 친구를 만나보세요.|Conheça seu companheiro antes de resgatar.|Познакомьтесь со спутником перед получением.|Conosci il compagno prima di sbloccarlo.
Equip companion|Usar este compañero|Diesen Begleiter wählen|Choisir ce compagnon|이 친구 적용|Usar este companheiro|Выбрать спутника|Usa questo compagno
Always free · No purchase needed|Siempre gratis · Sin compra|Immer kostenlos · Kein Kauf nötig|Toujours gratuit · Sans achat|항상 무료 · 구매 불필요|Sempre grátis · Sem compra|Всегда бесплатно · Покупка не нужна|Sempre gratis · Nessun acquisto
Use original companion|Volver al compañero original|Ursprünglichen Begleiter wählen|Revenir au compagnon original|기본 친구로 돌아가기|Voltar ao companheiro original|Вернуть первого спутника|Torna al compagno originale
After at least 60 seconds with a study, confirm your practice. The first 3 completions daily earn 10 stars and 20 XP each, once per study. This records practice, not performance accuracy.|Confirma tras al menos 60 segundos. Las primeras 3 prácticas diarias dan 10 estrellas y 20 XP cada una, una vez por partitura. Se registra la práctica, no la precisión.|Bestätige nach mindestens 60 Sekunden. Die ersten 3 Abschlüsse täglich geben je 10 Sterne und 20 XP, einmal pro Partitur. Erfasst wird Übungszeit, nicht Spielgenauigkeit.|Confirmez après au moins 60 secondes. Les 3 premières pratiques quotidiennes donnent chacune 10 étoiles et 20 XP, une fois par partition. Ce suivi mesure la pratique, pas la précision.|한 악보로 60초 이상 연습한 뒤 완료를 확인하세요. 매일 처음 3회에 각각 별 10개와 경험치 20을 받으며 같은 악보는 한 번만 계산합니다. 연주 정확도가 아닌 연습 기록입니다.|Confirme após pelo menos 60 segundos. As primeiras 3 práticas diárias dão 10 estrelas e 20 XP cada, uma vez por partitura. O registro mede prática, não precisão.|Подтвердите после 60 секунд. Первые 3 занятия за день дают по 10 звёзд и 20 XP, один раз на партитуру. Это запись практики, не точности игры.|Conferma dopo almeno 60 secondi. Le prime 3 pratiche giornaliere danno 10 stelle e 20 XP ciascuna, una volta per spartito. Si registra la pratica, non la precisione.
Stars are earned, never sold or redeemable for cash. Progress is stored in this browser.|Las estrellas se ganan, no se venden ni se canjean por dinero. El progreso se guarda en este navegador.|Sterne werden verdient, nicht verkauft oder ausgezahlt. Fortschritte bleiben in diesem Browser.|Les étoiles se gagnent, sans vente ni conversion en argent. Les progrès sont stockés dans ce navigateur.|별 포인트는 연습으로 얻으며 판매하거나 현금으로 바꿀 수 없습니다. 기록은 이 브라우저에 저장됩니다.|Estrelas são ganhas, não vendidas nem trocadas por dinheiro. O progresso fica neste navegador.|Звёзды зарабатываются, не продаются и не обмениваются на деньги. Прогресс хранится в браузере.|Le stelle si guadagnano, non si vendono né si convertono in denaro. I progressi restano in questo browser.
More music. Less friction.|Más música, con facilidad.|Mehr Musik. Leichter üben.|Plus de musique, en toute simplicité.|더 많은 음악을 편하게 즐겨요.|Mais música, com facilidade.|Больше музыки. Меньше сложностей.|Più musica, con semplicità.
A simple membership proposal. During development, generation stays open. No charges or practice limits are active.|Propuesta de suscripción sencilla. Durante el desarrollo, la generación es libre, sin cargos ni límites activos.|Ein einfacher Abo-Vorschlag. In der Entwicklung bleibt die Erzeugung offen, ohne Gebühren oder aktive Übungsgrenzen.|Une proposition d’abonnement simple. Pendant le développement, la génération reste libre, sans frais ni limites actives.|간단한 멤버십 제안입니다. 개발 중에는 자유롭게 생성할 수 있으며 결제나 연습 제한이 적용되지 않습니다.|Uma proposta simples de assinatura. Durante o desenvolvimento, a geração é livre, sem cobranças nem limites ativos.|Простой проект подписки. В разработке генерация свободна, оплата и ограничения не действуют.|Una proposta semplice di abbonamento. Durante lo sviluppo la generazione è libera, senza addebiti né limiti attivi.
Billing period|Periodo de facturación|Abrechnungszeitraum|Période de facturation|결제 주기|Período de cobrança|Период оплаты|Periodo di fatturazione
Monthly|Mensual|Monatlich|Mensuel|월간|Mensal|Ежемесячно|Mensile
Annual|Anual|Jährlich|Annuel|연간|Anual|Ежегодно|Annuale
Best value|Más económico|Günstiger|Plus avantageux|더 저렴해요|Mais econômico|Выгоднее|Più conveniente
A daily dose of music|Un poco de música cada día|Jeden Tag ein wenig Musik|Un peu de musique chaque jour|매일 조금씩 음악을|Um pouco de música por dia|Немного музыки каждый день|Un po’ di musica ogni giorno
3 new studies a day (planned)|3 partituras nuevas al día (previsto)|3 neue Übungen täglich (geplant)|3 nouvelles partitions par jour (prévu)|하루 새 악보 3개 (예정)|3 partituras novas por dia (planejado)|3 новые партитуры в день (планируется)|3 nuovi spartiti al giorno (previsto)
Revisit generated studies|Repetir partituras generadas|Erstellte Übungen wiederholen|Rejouer les partitions créées|생성한 악보 반복 연습|Repetir partituras geradas|Повторять созданные упражнения|Ripeti gli spartiti generati
Instruments, ranges & varied studies|Instrumentos, registros y variedad|Instrumente, Tonumfänge und Vielfalt|Instruments, tessitures et variété|악기, 음역 및 다양한 악보|Instrumentos, extensões e variedade|Инструменты, диапазоны и разнообразие|Strumenti, estensioni e varietà
Mimo and practice stars|Mimo y estrellas de práctica|Mimo und Übungssterne|Mimo et étoiles de pratique|미모와 연습 별 포인트|Mimo e estrelas de prática|Мимо и звёзды за практику|Mimo e stelle di pratica
Keep exploring|Seguir explorando|Weiter entdecken|Continuer à explorer|계속 둘러보기|Continuar explorando|Продолжить знакомство|Continua a esplorare
FOR YOUR PRACTICE JOURNEY|PARA TU CAMINO MUSICAL|FÜR DEINEN ÜBUNGSWEG|POUR VOTRE PARCOURS MUSICAL|꾸준한 연습을 위해|PARA SUA JORNADA MUSICAL|ДЛЯ ВАШЕГО МУЗЫКАЛЬНОГО ПУТИ|PER IL TUO PERCORSO MUSICALE
Room for every practice|Espacio para cada práctica|Raum für jede Übung|De la place pour chaque pratique|자유롭게 연습하세요|Espaço para toda prática|Место для каждого занятия|Spazio per ogni pratica
year|año|Jahr|an|년|ano|год|anno
month|mes|Monat|mois|월|mês|месяц|mese
Billed yearly · proposed price|Pago anual · precio propuesto|Jährliche Zahlung · Preisvorschlag|Paiement annuel · tarif proposé|연간 결제 · 제안 가격|Pagamento anual · preço proposto|Оплата за год · проект цены|Pagamento annuale · prezzo proposto
Billed monthly · proposed price|Pago mensual · precio propuesto|Monatliche Zahlung · Preisvorschlag|Paiement mensuel · tarif proposé|월간 결제 · 제안 가격|Pagamento mensal · preço proposto|Оплата за месяц · проект цены|Pagamento mensile · prezzo proposto
Unlimited new studies (planned)|Partituras ilimitadas (previsto)|Unbegrenzte Übungen (geplant)|Partitions illimitées (prévu)|새 악보 무제한 생성 (예정)|Partituras ilimitadas (planejado)|Неограниченные партитуры (планируется)|Spartiti illimitati (previsto)
Long-term progress insights (planned)|Análisis de progreso a largo plazo (previsto)|Langfristige Fortschrittsanalyse (geplant)|Analyse des progrès à long terme (prévu)|장기 성장 분석 (예정)|Análise de progresso a longo prazo (planejado)|Долгосрочный анализ прогресса (планируется)|Analisi dei progressi nel tempo (previsto)
Personal practice plans (planned)|Planes personales de práctica (previsto)|Persönliche Übungspläne (geplant)|Plans de pratique personnalisés (prévu)|개인 연습 계획 (예정)|Planos pessoais de prática (planejado)|Личные планы занятий (планируется)|Piani personali di pratica (previsto)
Cross-device sync (planned)|Sincronización entre dispositivos (previsto)|Geräteübergreifende Synchronisierung (geplant)|Synchronisation entre appareils (prévu)|기기 간 동기화 (예정)|Sincronização entre dispositivos (planejado)|Синхронизация устройств (планируется)|Sincronizzazione tra dispositivi (previsto)
Purchases not available yet|Compras aún no disponibles|Kauf noch nicht verfügbar|Achats pas encore disponibles|아직 구매할 수 없습니다|Compras ainda indisponíveis|Покупки пока недоступны|Acquisti non ancora disponibili
Regional prices, renewal and cancellation terms will be confirmed before launch. Assessment accuracy is still being validated.|Precios regionales, renovación y cancelación se confirmarán antes del lanzamiento. La precisión de la evaluación sigue en validación.|Regionale Preise, Verlängerung und Kündigung werden vor dem Start festgelegt. Die Testgenauigkeit wird noch geprüft.|Tarifs régionaux, renouvellement et résiliation seront confirmés avant le lancement. La précision de l’évaluation est encore en validation.|출시 전에 지역별 가격, 갱신 및 해지 조건을 확정합니다. 평가 정확도는 아직 검증 중입니다.|Preços regionais, renovação e cancelamento serão confirmados antes do lançamento. A precisão da avaliação ainda está sendo validada.|Региональные цены, продление и отмена будут определены до запуска. Точность оценки ещё проверяется.|Prezzi regionali, rinnovo e cancellazione saranno confermati prima del lancio. L’accuratezza della valutazione è ancora in verifica.
A little space for music.|Un momento para la música.|Ein wenig Raum für Musik.|Un peu de place pour la musique.|음악을 위한 작은 여유.|Um espaço para a música.|Немного места для музыки.|Un po’ di spazio per la musica.
YOUR DAILY READING RITUAL|TU LECTURA MUSICAL DIARIA|DEIN TÄGLICHES BLATTSPIEL|VOTRE LECTURE MUSICALE QUOTIDIENNE|매일의 독보 시간|SUA LEITURA MUSICAL DIÁRIA|ЕЖЕДНЕВНОЕ ЧТЕНИЕ НОТ|LA TUA LETTURA MUSICALE QUOTIDIANA
Find your next note.|Descubre la siguiente nota.|Finde deinen nächsten Ton.|Trouvez votre prochaine note.|다음 음을 읽고,|Encontre sua próxima nota.|Найдите следующую ноту.|Trova la tua prossima nota.
Find your own rhythm.|Encuentra tu propio ritmo.|Finde deinen eigenen Rhythmus.|Trouvez votre propre rythme.|나만의 리듬을 찾아요.|Encontre seu próprio ritmo.|Найдите свой ритм.|Trova il tuo ritmo.
Begin with your instrument and a comfortable range. Make a little practice something to look forward to.|Empieza con tu instrumento y un registro cómodo. Haz que practicar sea un pequeño placer diario.|Beginne mit deinem Instrument und einem bequemen Tonumfang. Mach eine kleine Übung zur täglichen Vorfreude.|Commencez avec votre instrument et une tessiture confortable. Faites de la pratique un petit plaisir quotidien.|악기와 편안한 음역부터 시작하세요. 짧은 연습을 매일 기대되는 시간으로 만들어 보세요.|Comece com seu instrumento e uma extensão confortável. Faça da prática um prazer diário.|Начните с инструмента и удобного диапазона. Пусть небольшое занятие станет приятной частью дня.|Inizia con il tuo strumento e un’estensione comoda. Rendi la pratica un piccolo piacere quotidiano.
Start today’s practice|Empezar la práctica de hoy|Heutige Übung starten|Commencer la pratique du jour|오늘의 연습 시작|Começar a prática de hoje|Начать сегодняшнее занятие|Inizia la pratica di oggi
INSTRUMENT|INSTRUMENTO|INSTRUMENT|INSTRUMENT|악기 선택|INSTRUMENTO|ИНСТРУМЕНТ|STRUMENTO
CHALLENGE|RETO|HERAUSFORDERUNG|DÉFI|난이도 설정|DESAFIO|ЗАДАНИЕ|SFIDA
PLAY|TOCAR|SPIELEN|JOUER|연주하기|TOCAR|ИГРАТЬ|SUONA
A study that meets you where you are.|Un ejercicio adaptado a tu nivel.|Eine Übung passend zu deinem Können.|Un exercice adapté à votre niveau.|지금의 실력에 맞는 연습이에요.|Um estudo para o seu nível.|Упражнение под ваш уровень.|Uno studio adatto al tuo livello.
Make room for a habit.|Haz de la práctica un hábito.|Mach Üben zur Gewohnheit.|Faites de la pratique une habitude.|연습을 일상으로 만들어요.|Faça da prática um hábito.|Превратите практику в привычку.|Fai della pratica un’abitudine.
LAST 7 DAYS|ÚLTIMOS 7 DÍAS|LETZTE 7 TAGE|7 DERNIERS JOURS|최근 7일|ÚLTIMOS 7 DIAS|ПОСЛЕДНИЕ 7 ДНЕЙ|ULTIMI 7 GIORNI
Practiced|Practicado|Geübt|Pratiqué|연습함|Praticado|Практика выполнена|Praticato
No practice yet|Sin práctica aún|Noch nicht geübt|Pas encore pratiqué|아직 연습하지 않음|Ainda sem prática|Пока без практики|Non ancora praticato
Today|Hoy|Heute|Aujourd’hui|오늘|Hoje|Сегодня|Oggi
Earn stars for your first 3 practices each day|Gana estrellas en tus primeras 3 prácticas diarias|Sterne für die ersten 3 Übungen täglich|Des étoiles pour les 3 premières pratiques du jour|매일 처음 3회 연습에 별 포인트를 받아요|Ganhe estrelas nas primeiras 3 práticas do dia|Звёзды за первые 3 занятия в день|Stelle per le prime 3 pratiche del giorno
More room to grow.|Más espacio para mejorar.|Mehr Raum zum Wachsen.|Plus de place pour progresser.|더 많은 성장의 가능성.|Mais espaço para evoluir.|Больше возможностей для роста.|Più spazio per crescere.
Unlimited studies and long-term progress insights are on our roadmap. Explore our simple membership proposal.|Planeamos partituras ilimitadas y análisis del progreso. Descubre nuestra propuesta de suscripción.|Unbegrenzte Übungen und langfristige Fortschritte sind geplant. Entdecke unseren Abo-Vorschlag.|Partitions illimitées et suivi à long terme sont prévus. Découvrez notre proposition d’abonnement.|무제한 악보와 장기 성장 분석을 준비 중입니다. 간단한 멤버십 제안을 살펴보세요.|Planejamos partituras ilimitadas e análise do progresso. Conheça nossa proposta de assinatura.|Мы планируем неограниченные упражнения и анализ прогресса. Ознакомьтесь с проектом подписки.|Prevediamo spartiti illimitati e analisi dei progressi. Scopri la proposta di abbonamento.
Explore membership|Ver suscripción|Mitgliedschaft entdecken|Découvrir l’abonnement|멤버십 살펴보기|Explorar assinatura|Посмотреть подписку|Scopri l’abbonamento
DEVELOPMENT PREVIEW · NO CHARGES|VISTA DE DESARROLLO · SIN CARGOS|ENTWICKLUNGSVORSCHAU · KOSTENLOS|APERÇU EN DÉVELOPPEMENT · SANS FRAIS|개발 미리 보기 · 현재 무료|PRÉVIA DE DESENVOLVIMENTO · SEM COBRANÇA|ВЕРСИЯ В РАЗРАБОТКЕ · БЕЗ ОПЛАТЫ|ANTEPRIMA DI SVILUPPO · SENZA ADDEBITI
No race, no pressure. Just one more note than yesterday.|Sin prisa ni presión. Solo una nota más que ayer.|Kein Rennen, kein Druck. Nur ein Ton mehr als gestern.|Sans course ni pression. Juste une note de plus qu’hier.|남과 비교하지 않아도 돼요. 어제보다 한 음만 더 읽어봐요.|Sem corrida nem pressão. Só uma nota a mais que ontem.|Без гонки и давления. Всего на ноту больше, чем вчера.|Nessuna gara, nessuna pressione. Solo una nota in più di ieri.
THE DAILY STUDIO|EL ESTUDIO DIARIO|DAS TÄGLICHE STUDIO|LE STUDIO AU QUOTIDIEN|오늘의 연습실|O ESTÚDIO DIÁRIO|ЕЖЕДНЕВНАЯ СТУДИЯ|LO STUDIO QUOTIDIANO
SMALL STEPS, REAL PROGRESS|PASOS PEQUEÑOS, PROGRESO REAL|KLEINE SCHRITTE, ECHTER FORTSCHRITT|PETITS PAS, VRAIS PROGRÈS|작은 걸음, 확실한 성장|PEQUENOS PASSOS, PROGRESSO REAL|МАЛЕНЬКИЕ ШАГИ, НАСТОЯЩИЙ ПРОГРЕСС|PICCOLI PASSI, VERI PROGRESSI
PRACTICE STUDIO|ESTUDIO DE PRÁCTICA|ÜBUNGSSTUDIO|STUDIO DE PRATIQUE|음악 연습실|ESTÚDIO DE PRÁTICA|СТУДИЯ ПРАКТИКИ|STUDIO DI PRATICA
YOUR PRACTICE ROOM|TU SALA DE PRÁCTICA|DEIN ÜBUNGSRAUM|VOTRE SALLE DE PRATIQUE|나의 연습실|SUA SALA DE PRÁTICA|ВАША КОМНАТА ПРАКТИКИ|LA TUA SALA DI PRATICA
SESSION|SESIÓN|SITZUNG|SÉANCE|세션|SESSÃO|ЗАНЯТИЕ|SESSIONE
SIGHT-READING STUDY|EJERCICIO DE LECTURA|BLATTSPIELÜBUNG|EXERCICE DE DÉCHIFFRAGE|초견 연습|ESTUDO DE LEITURA À PRIMEIRA VISTA|УПРАЖНЕНИЕ ПО ЧТЕНИЮ С ЛИСТА|STUDIO DI LETTURA A PRIMA VISTA
LEVEL|NIVEL|STUFE|NIVEAU|레벨|NÍVEL|УРОВЕНЬ|LIVELLO
STEP|PASO|SCHRITT|ÉTAPE|단계|ETAPA|ШАГ|PASSAGGIO
`.trim().split('\n').map(row => { const [key, ...values] = row.split('|'); return [key, values]; }));
