// English source text -> es, de, fr, ko, pt-BR, ru, it.
export const companionText: Record<string, readonly string[]> = Object.fromEntries(`
Mimo|Mimo|Mimo|Mimo|미모|Mimo|Мимо|Mimo
Lark|Alondra|Lerche|Alouette|종달새|Cotovia|Жаворонок|Allodola
Music Fox|Zorro Musical|Musikfuchs|Renard Musical|음악 여우|Raposa Musical|Музыкальный лис|Volpe Musicale
Music fox|Zorro Musical|Musikfuchs|Renard Musical|음악 여우|Raposa Musical|Музыкальный лис|Volpe Musicale
Raccoon|Mapache|Waschbär|Raton laveur|라쿤|Guaxinim|Енот|Procione
Moon Bunny|Conejo Lunar|Mondhase|Lapin Lunaire|달토끼|Coelho Lunar|Лунный зайчик|Coniglio Lunare
Nocturne Cat|Gato Nocturno|Nachtkatze|Chat Nocturne|야상곡 고양이|Gato Noturno|Ночной кот|Gatto Notturno
Bamboo Panda|Panda Bambú|Bambuspanda|Panda Bambou|대나무 판다|Panda Bambu|Бамбуковая панда|Panda Bambù
Polar Penguin|Pingüino Polar|Polarpinguin|Manchot Polaire|극지 펭귄|Pinguim Polar|Полярный пингвин|Pinguino Polare
Companion|Compañero|Begleiter|Compagnon|친구|Companheiro|Спутник|Compagno
Metronome companion|Compañero metrónomo|Metronom-Begleiter|Compagnon métronome|메트로놈 친구|Companheiro metrônomo|Друг-метроном|Compagno metronomo
Today’s practice|Práctica de hoy|Heutige Übung|Pratique du jour|오늘의 연습|Prática de hoje|Сегодняшняя практика|Pratica di oggi
Today’s goal is complete. Nicely done.|Objetivo de hoy cumplido. ¡Buen trabajo!|Tagesziel erreicht. Gut gemacht!|Objectif du jour atteint. Bravo !|오늘 목표를 달성했어요. 잘했어요!|Meta de hoje concluída. Muito bem!|Цель на сегодня достигнута. Отлично!|Obiettivo di oggi raggiunto. Bravo!
Stars|Estrellas|Sterne|Étoiles|별 포인트|Estrelas|Звёзды|Stelle
Explore rewards|Explorar recompensas|Belohnungen entdecken|Découvrir les récompenses|보상 살펴보기|Explorar recompensas|Посмотреть награды|Scopri le ricompense
Right here, while you focus.|Aquí estoy, mientras te concentras.|Ich bin hier, während du dich konzentrierst.|Je reste là pendant que tu te concentres.|집중하는 동안 곁에 있을게요.|Estou aqui enquanto você se concentra.|Я рядом, пока ты сосредоточен.|Sono qui mentre ti concentri.
Tap {name} for a practice tip|Toca a {name} para un consejo|Tippe auf {name} für einen Übungstipp|Touchez {name} pour un conseil|{name} 터치: 연습 팁 보기|Toque em {name} para uma dica|Нажмите на {name}, чтобы получить совет|Tocca {name} per un consiglio
A little tap. A little inspiration.|Un toque, un poco de inspiración.|Ein kleiner Tipp, etwas Inspiration.|Un petit geste, un peu d’inspiration.|살짝 눌러 연습 영감을 얻어봐요.|Um toque, um pouco de inspiração.|Одно касание — немного вдохновения.|Un piccolo tocco, un po’ d’ispirazione.
Read the meter and key, then hear the first phrase in your head. There’s no rush.|Mira el compás y la armadura, e imagina la primera frase. No hay prisa.|Lies Taktart und Vorzeichen und höre die erste Phrase im Kopf. Lass dir Zeit.|Lisez la mesure et l’armure, puis écoutez la première phrase dans votre tête. Rien ne presse.|박자표와 조표를 확인한 뒤 첫 악구를 마음속으로 들어보세요. 서두르지 않아도 돼요.|Veja o compasso e a armadura e imagine a primeira frase. Sem pressa.|Посмотрите размер и ключевые знаки, затем услышьте первую фразу мысленно. Не спешите.|Leggi metro e armatura e ascolta mentalmente la prima frase. Non c’è fretta.
Choose a tempo you can sustain. Give a steady pulse room to grow.|Elige un tempo que puedas mantener. Deja crecer un pulso estable.|Wähle ein Tempo, das du durchhältst. Gib einem gleichmäßigen Puls Raum.|Choisissez un tempo que vous pouvez tenir. Laissez une pulsation régulière s’installer.|끝까지 유지할 수 있는 속도를 선택하세요. 일정한 박자부터 익혀봐요.|Escolha um andamento que consiga manter. Deixe o pulso estável crescer.|Выберите темп, который сможете удержать. Дайте ровному пульсу закрепиться.|Scegli un tempo sostenibile. Lascia crescere una pulsazione regolare.
Take a tricky passage one phrase at a time: tap the rhythm, then add the notes.|Divide el pasaje difícil en frases: marca el ritmo y luego añade notas.|Teile schwierige Stellen in Phrasen: klopfe den Rhythmus, dann ergänze Töne.|Découpez le passage difficile en phrases : frappez le rythme, puis ajoutez les notes.|어려운 부분은 짧은 악구로 나누세요. 리듬을 먼저 치고 음을 추가하세요.|Divida o trecho difícil em frases: bata o ritmo e acrescente as notas.|Разберите сложное место по фразам: сначала простучите ритм, затем добавьте ноты.|Dividi il passaggio difficile in frasi: batti il ritmo, poi aggiungi le note.
A little today, a little tomorrow. Before you finish, notice one thing that felt easier.|Un poco hoy, un poco mañana. Antes de terminar, observa algo que resulte más fácil.|Heute ein wenig, morgen wieder. Bemerke vor dem Ende etwas, das leichter ging.|Un peu aujourd’hui, un peu demain. Avant de finir, notez ce qui est devenu plus facile.|오늘 조금, 내일 또 조금씩 해봐요. 끝내기 전에 더 수월해진 부분을 하나 떠올려보세요.|Um pouco hoje, um pouco amanhã. Antes de terminar, perceba algo que ficou mais fácil.|Немного сегодня, немного завтра. Перед завершением отметьте то, что стало легче.|Un po’ oggi, un po’ domani. Prima di finire, nota qualcosa che è diventato più facile.
A companion that joins each practice session|Un compañero para cada práctica|Ein Begleiter für jede Übung|Un compagnon pour chaque pratique|매번 연습을 함께하는 친구|Um companheiro para cada prática|Спутник для каждого занятия|Un compagno per ogni pratica
Helps you stay focused during longer runs|Te acompaña en prácticas largas|Begleitet dich bei längeren Übungen|Vous accompagne dans les longues pratiques|긴 연습에도 함께하는 친구|Acompanha práticas mais longas|Рядом во время долгих занятий|Ti accompagna nelle pratiche più lunghe
Rewards rhythm work with small cheer prompts|Te anima a seguir el ritmo|Ermuntert dich beim Rhythmusüben|Vous encourage à garder le rythme|리듬 연습을 응원하는 친구|Incentiva sua prática rítmica|Подбадривает при работе над ритмом|Ti incoraggia nella pratica ritmica
A cream-colored bunny with long rose-lined ears.|Un conejo crema con largas orejas rosadas.|Ein cremefarbener Hase mit langen rosa Ohren.|Un lapin crème aux longues oreilles rosées.|장밋빛 긴 귀를 가진 크림색 토끼.|Um coelho creme com longas orelhas rosadas.|Кремовый зайчик с длинными розовыми ушами.|Un coniglio crema con lunghe orecchie rosate.
A midnight-blue cat with amber eyes and a curled tail.|Un gato azul nocturno de ojos ámbar y cola rizada.|Eine nachtblaue Katze mit Bernsteinaugen und geringeltem Schwanz.|Un chat bleu nuit aux yeux ambrés et à la queue enroulée.|호박색 눈과 말린 꼬리를 가진 짙은 파란 고양이.|Um gato azul-noturno de olhos âmbar e cauda enrolada.|Ночной синий кот с янтарными глазами и загнутым хвостом.|Un gatto blu notte con occhi ambrati e coda arricciata.
A round panda with a bamboo-green metronome.|Un panda redondo con metrónomo verde bambú.|Ein runder Panda mit bambusgrünem Metronom.|Un panda tout rond au métronome vert bambou.|대나무색 메트로놈을 가진 동글동글 판다.|Um panda redondo com metrônomo verde-bambu.|Круглая панда с бамбуково-зелёным метрономом.|Un panda rotondo con metronomo verde bambù.
An ice-blue scarf and tiny orange feet keep the beat.|Bufanda azul hielo y patitas naranjas al ritmo.|Ein eisblauer Schal und kleine orange Füße im Takt.|Une écharpe bleu glacier et de petites pattes orange en rythme.|하늘색 목도리와 작은 주황 발로 박자를 맞춰요.|Cachecol azul-gelo e patinhas laranjas no ritmo.|Ледяной голубой шарф и оранжевые лапки держат ритм.|Sciarpa azzurro ghiaccio e piedini arancioni a tempo.
Use it like an app|Úsalo como una aplicación|Wie eine App verwenden|Utilisez-le comme une application|앱처럼 사용하기|Use como aplicativo|Используйте как приложение|Usalo come un’app
Add this page to your home screen for a smoother full-screen app experience.|Añade esta página a la pantalla de inicio para usarla a pantalla completa.|Füge diese Seite zum Startbildschirm hinzu, um sie im Vollbild zu nutzen.|Ajoutez cette page à l’écran d’accueil pour l’utiliser en plein écran.|홈 화면에 추가하면 전체 화면으로 더 편하게 사용할 수 있어요.|Adicione à tela inicial para usar em tela cheia.|Добавьте страницу на главный экран для работы в полноэкранном режиме.|Aggiungi la pagina alla schermata iniziale per usarla a schermo intero.
I added to home screen|Ya la añadí al inicio|Zum Startbildschirm hinzugefügt|Ajouté à l’écran d’accueil|홈 화면에 추가했어요|Já adicionei à tela inicial|Добавлено на главный экран|Aggiunto alla schermata iniziale
Start today|Empezar hoy|Heute beginnen|Commencer aujourd’hui|오늘 시작하기|Começar hoje|Начать сегодня|Inizia oggi
Not now|Ahora no|Nicht jetzt|Pas maintenant|나중에|Agora não|Не сейчас|Non ora
`.trim().split('\n').map(row => { const [key, ...values] = row.split('|'); return [key, values]; }));
