export const layoutMessages={
  layoutSize:['版面大小','Layout size','表示サイズ','Tamaño de interfaz','Layoutgröße','Taille de l’interface','화면 크기','Tamanho da interface','Размер интерфейса','Dimensione interfaccia'],
  layoutCompact:['緊湊','Compact','コンパクト','Compacto','Kompakt','Compact','촘촘하게','Compacto','Компактный','Compatta'],
  layoutStandard:['標準','Standard','標準','Estándar','Standard','Standard','기본','Padrão','Стандартный','Standard'],
  layoutComfortable:['寬鬆','Spacious','ゆったり','Amplio','Großzügig','Spacieux','여유롭게','Espaçoso','Просторный','Spaziosa'],
  layoutHelp:['隨時調整標題大小與版面間距。五線譜保留原本比例，確保清楚好讀。','Adjust heading sizes and spacing anytime. Notation keeps its original proportions for clear reading.','見出しと余白をいつでも調整できます。譜面の比率は変わりません。','Ajusta títulos y espacios. La notación mantiene sus proporciones para facilitar la lectura.','Überschriften und Abstände anpassen. Die Noten behalten ihre gut lesbaren Proportionen.','Ajustez les titres et les espacements. La notation conserve ses proportions pour rester lisible.','제목 크기와 여백을 조절하세요. 악보는 읽기 쉽도록 원래 비율을 유지해요.','Ajuste títulos e espaçamento. A notação mantém suas proporções para facilitar a leitura.','Настройте заголовки и отступы. Пропорции нот сохраняются для удобного чтения.','Regola titoli e spazi. La notazione mantiene le proporzioni originali per una lettura chiara.'],
  layoutSaved:['已自動記住版面，下次開啟會沿用。','Layout remembered for your next visit.','次回もこの表示設定を使います。','La interfaz se guardó para la próxima visita.','Layout für den nächsten Besuch gespeichert.','Interface mémorisée pour votre prochaine visite.','다음 방문에도 이 설정을 사용해요.','Interface salva para a próxima visita.','Настройка сохранена для следующего посещения.','Impostazione salvata per la prossima visita.'],
  layoutSaveWarning:['本次已套用，但瀏覽器無法儲存設定。','Applied now, but browser storage is unavailable.','適用しましたが、ブラウザに保存できません。','Aplicado, pero no se pudo guardar en el navegador.','Angewendet, aber der Browser kann nicht speichern.','Appliqué, mais le navigateur ne peut pas enregistrer.','적용했지만 브라우저에 저장할 수 없어요.','Aplicado, mas não foi possível salvar no navegador.','Применено, но браузер не может сохранить настройку.','Applicato, ma il browser non può salvare.'],
} as const;
