// Traditional Chinese, English, Japanese, Spanish, German, French, Korean, Portuguese, Russian, Italian.
export const tuningMessages = {
  tuningFork: ['音叉', 'Tuning fork', '音叉', 'Diapasón', 'Stimmgabel', 'Diapason', '소리굽쇠', 'Diapasão', 'Камертон', 'Diapason'],
  tuningClose: ['關閉音叉', 'Close tuning fork', '音叉を閉じる', 'Cerrar diapasón', 'Stimmgabel schließen', 'Fermer le diapason', '소리굽쇠 닫기', 'Fechar diapasão', 'Закрыть камертон', 'Chiudi diapason'],
  tuningFrequency: ['基準頻率', 'Reference frequency', '基準周波数', 'Frecuencia de referencia', 'Referenzfrequenz', 'Fréquence de référence', '기준 주파수', 'Frequência de referência', 'Опорная частота', 'Frequenza di riferimento'],
  tuningHelp: ['以 A4 純音對音，可依樂團標準調整。此設定僅用於音叉。', 'Tune to a pure A4 tone and adjust it to your ensemble’s reference. This setting applies only to the tuning fork.', 'A4の純音で調律します。合奏の基準に合わせて調整できます。この設定は音叉のみのものです。', 'Afina con un tono puro de La4 y ajústalo a tu conjunto. Este ajuste solo afecta al diapasón.', 'Stimme mit einem reinen A4-Ton nach dem Referenzton deines Ensembles. Diese Einstellung gilt nur für die Stimmgabel.', 'Accordez-vous sur un son pur de La4, ajustable selon votre ensemble. Ce réglage concerne uniquement le diapason.', '순수한 A4 음으로 조율하고 합주 기준에 맞게 조정하세요. 이 설정은 소리굽쇠에만 적용됩니다.', 'Afine com um tom puro de Lá4, ajustável à referência do seu grupo. Esta configuração afeta apenas o diapasão.', 'Настраивайтесь по чистому тону ля первой октавы (A4). Частоту можно изменить под строй ансамбля. Настройка действует только на камертон.', 'Accorda su un tono puro di La4, regolabile secondo il tuo ensemble. Questa impostazione vale solo per il diapason.'],
  tuningPlay: ['播放對音', 'Play reference', '基準音を鳴らす', 'Escuchar referencia', 'Referenzton spielen', 'Jouer la référence', '기준음 재생', 'Ouvir referência', 'Включить тон', 'Suona riferimento'],
  tuningStop: ['停止對音', 'Stop reference', '基準音を止める', 'Detener referencia', 'Referenzton stoppen', 'Arrêter la référence', '기준음 정지', 'Parar referência', 'Выключить тон', 'Ferma riferimento'],
  tuningReset: ['重設 440 Hz', 'Reset 440 Hz', '440 Hzに戻す', 'Restablecer 440 Hz', 'Auf 440 Hz setzen', 'Rétablir 440 Hz', '440 Hz로 초기화', 'Redefinir 440 Hz', 'Вернуть 440 Гц', 'Ripristina 440 Hz'],
  tuningPlaying: ['對音中', 'Reference playing', '基準音を再生中', 'Referencia sonando', 'Referenzton läuft', 'Référence en cours', '기준음 재생 중', 'Referência tocando', 'Тон включён', 'Riferimento in riproduzione'],
  tuningSaved: ['會自動記住頻率設定。', 'Frequency changes are saved automatically.', '周波数の変更は自動保存されます。', 'Los cambios de frecuencia se guardan automáticamente.', 'Frequenzänderungen werden automatisch gespeichert.', 'Les changements de fréquence sont enregistrés automatiquement.', '주파수 변경 사항은 자동으로 저장됩니다.', 'As alterações de frequência são salvas automaticamente.', 'Изменения частоты сохраняются автоматически.', 'Le modifiche alla frequenza vengono salvate automaticamente.'],
  tuningTemporary: ['目前無法儲存，關閉後可能需重設。', 'Cannot save right now; you may need to set this again next time.', '現在保存できません。次回は再設定が必要な場合があります。', 'No se puede guardar ahora; quizá debas ajustarlo de nuevo la próxima vez.', 'Speichern derzeit nicht möglich. Eventuell musst du den Wert später erneut einstellen.', 'Enregistrement impossible pour le moment. Il faudra peut-être régler à nouveau la fréquence.', '지금은 저장할 수 없습니다. 다음에 다시 설정해야 할 수 있습니다.', 'Não foi possível salvar agora. Talvez seja necessário ajustar novamente depois.', 'Сохранение недоступно. Возможно, в следующий раз придётся настроить заново.', 'Impossibile salvare ora. Potresti dover impostare di nuovo la frequenza.'],
  tuningError: ['無法啟動音叉，請再次點擊播放對音。', 'Could not start the tuning fork. Tap Play reference to retry.', '音叉を開始できません。基準音の再生をもう一度押してください。', 'No se pudo iniciar el diapasón. Pulsa Escuchar referencia para reintentar.', 'Die Stimmgabel konnte nicht starten. Drücke erneut auf Referenzton spielen.', 'Impossible de démarrer le diapason. Appuyez sur Jouer la référence pour réessayer.', '소리굽쇠를 시작할 수 없습니다. 기준음 재생을 눌러 다시 시도하세요.', 'Não foi possível iniciar o diapasão. Toque em Ouvir referência para tentar novamente.', 'Не удалось включить камертон. Нажмите «Включить тон» ещё раз.', 'Impossibile avviare il diapason. Tocca Suona riferimento per riprovare.'],
} as const;
