import {useI18n} from '../i18n/context';
import {NoteCompanion} from './NoteCompanion';
import {dayKey,type ProgressState,getLevel} from '../progress/progress';
import {words} from '../progress/words';
export default function StudioHome({progress,onStart,onRewards,onPlans}:{progress:ProgressState;onStart:()=>void;onRewards:()=>void;onPlans:()=>void}){
  const {locale}=useI18n();const w=(zh:string,en:string,ja:string)=>words(locale,zh,en,ja);
  const level=getLevel(progress.xp);
  const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return {key:dayKey(d),label:new Intl.DateTimeFormat(locale,{weekday:'short'}).format(d)};});
  return <main className="studio-home" id="main">
    <div className="home-heading"><div><span className="studio-kicker">{w('每日練習室','THE DAILY STUDIO','毎日の練習室')}</span><h1>{w('留一點時間，給音樂。','A little space for music.','音楽のための、ひととき。')}</h1></div><span className="home-date">{new Intl.DateTimeFormat(locale,{month:'long',day:'numeric',weekday:'long'}).format(new Date())}</span></div>
    <div className="home-hero-grid"><section className="welcome-card"><div className="hero-staff" aria-hidden="true"><i/><i/><i/><i/><i/><span>♪</span><b>♩</b></div><div className="hero-content"><span className="studio-pill"><i/>{w('你的每日讀譜時光','YOUR DAILY READING RITUAL','毎日の読譜習慣')}</span><h2>{w('讀懂下一個音，','Find your next note.','次の音を見つける。')}<br/><em>{w('遇見更好的自己。','Find your own rhythm.','自分のリズムで。')}</em></h2><p>{w('從適合你的樂器與音域開始。讓一段小小的練習，成為每天值得期待的事。','Begin with your instrument and a comfortable range. Make a little practice something to look forward to.','楽器と無理のない音域から。小さな練習を、毎日の楽しみに。')}</p><button className="studio-cta" onClick={onStart}>{w('開始今日練習','Start today’s practice','今日の練習を始める')}<span aria-hidden="true">↗</span></button><div className="hero-specs"><span>01 <b>{w('選擇樂器','INSTRUMENT','楽器')}</b></span><span>02 <b>{w('設定挑戰','CHALLENGE','設定')}</b></span><span>03 <b>{w('專注讀譜','PLAY','演奏')}</b></span></div></div><div className="hero-bottom"><span>{w('為你的程度，準備剛剛好的練習。','A study that meets you where you are.','今のあなたに合う練習を。')}</span><span aria-hidden="true">𝄞</span></div></section>
      <NoteCompanion level={level.level} points={progress.points} todayCount={progress.today.count} dailyGoal={3} pet={progress.activePet} onRewards={onRewards}/></div>
    <div className="home-details-grid"><section className="journey-card"><div className="section-title"><div><span className="studio-kicker">{w('小小累積，真實進步','SMALL STEPS, REAL PROGRESS','小さな一歩、確かな進歩')}</span><h2>{w('把練習，變成日常。','Make room for a habit.','練習を、日常に。')}</h2></div><span className="soft-label">{w('最近 7 天','LAST 7 DAYS','過去7日間')}</span></div><div className="week-days">{days.map((day,i)=><div className={progress.practiceDays.includes(day.key)?'day-complete':i===6?'day-today':''} key={day.key}><span>{day.label}</span><b aria-label={progress.practiceDays.includes(day.key)?w('已練習','Practiced','練習済み'):w('尚未練習','No practice yet','未練習')}>{progress.practiceDays.includes(day.key)?'✓':i===6?'♪':'·'}</b></div>)}</div><div className="journey-footer"><span>{w('今天完成','Today','今日')} <strong>{progress.today.count} / 3</strong></span><span>{w('每天前 3 次練習可獲得星點','Earn stars for your first 3 practices each day','毎日最初の3回でスターを獲得')}</span></div></section>
    <section className="membership-teaser"><span className="studio-kicker">SIGHT READING PLUS</span><h2>{w('讓進步，有更多可能。','More room to grow.','もっと自由に、上達を。')}</h2><p>{w('我們正在設計不限出題與長期進步追蹤。先看看簡單、透明的方案構想。','Unlimited studies and long-term progress insights are on our roadmap. Explore our simple membership proposal.','出題無制限と長期的な進歩の記録を計画中。シンプルなプラン案をご覧ください。')}</p><button className="studio-text-link" onClick={onPlans}>{w('探索會員方案','Explore membership','プランを見る')} <span aria-hidden="true">→</span></button><span className="prototype-note">{w('開發預覽・目前不收費','DEVELOPMENT PREVIEW · NO CHARGES','開発プレビュー・課金なし')}</span></section></div>
    <p className="home-bottom-note">{w('不必追趕別人的進度。今天，比昨天多讀懂一點就好。','No race, no pressure. Just one more note than yesterday.','誰かと競わなくていい。昨日より、ひとつ先の音へ。')}</p>
  </main>;
}
